name: falconup-40
services:
  nginx:
    container_name: falconup-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/log:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - falconup

  backend:
    container_name: falconup-backend
    image: falconup-backend
    build:
      context: ../backend
      dockerfile: ../ops/Dockerfile.backend
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - falconup

  frontend:
    container_name: falconup-frontend
    image: falconup-frontend
    build:
      context: ../frontend
      dockerfile: ../ops/Dockerfile.frontend
      args:
        - NEXT_PUBLIC_FASTAPI_SERVER=${NEXT_PUBLIC_FASTAPI_SERVER}
        - NEXT_PUBLIC_BETTER_AUTH_URL=${NEXT_PUBLIC_BETTER_AUTH_URL}
    restart: unless-stopped
    env_file:
      - ../.env
    depends_on:
      - backend
    networks:
      - falconup

networks:
  falconup:
    driver: bridge
