services:
  backend:
    build:
      context: ../backend
      dockerfile: ../ops/Dockerfile.backend
    restart: unless-stopped
    ports:
      - "${FASTAPI_PORT:-40401}:40401"
    env_file:
      - ../.env

  frontend:
    build:
      context: ../frontend
      dockerfile: ../ops/Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-4040}:4040"
    env_file:
      - ../.env
    environment:
      NEXT_PUBLIC_FASTAPI_SERVER: http://localhost:${FASTAPI_PORT:-40401}
    depends_on:
      - backend
